/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : string,
  'status' : string,
  'timeIn' : string,
  'employeeName' : string,
  'date' : string,
  'employeeId' : string,
  'timestamp' : bigint,
  'department' : string,
}
export interface AttendanceStats {
  'total' : bigint,
  'present' : bigint,
  'absent' : bigint,
}
export interface Employee {
  'id' : string,
  'name' : string,
  'employeeIdCode' : string,
  'department' : string,
}
export interface FaceDescriptorRecord {
  'descriptor' : Array<number>,
  'employeeId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAttendanceLogs' : ActorMethod<[], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'getAllAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllFaceDescriptors' : ActorMethod<[], Array<FaceDescriptorRecord>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByEmployee' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceStats' : ActorMethod<[string], AttendanceStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], Employee>,
  'getFaceDescriptor' : ActorMethod<[string], Array<number>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveFaceDescriptor' : ActorMethod<[string, Array<number>], undefined>,
  'updateEmployee' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];