/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'timeIn' : IDL.Text,
  'employeeName' : IDL.Text,
  'date' : IDL.Text,
  'employeeId' : IDL.Text,
  'timestamp' : IDL.Int,
  'department' : IDL.Text,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'employeeIdCode' : IDL.Text,
  'department' : IDL.Text,
});
export const FaceDescriptorRecord = IDL.Record({
  'descriptor' : IDL.Vec(IDL.Float64),
  'employeeId' : IDL.Text,
});
export const AttendanceStats = IDL.Record({
  'total' : IDL.Nat,
  'present' : IDL.Nat,
  'absent' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAttendanceLogs' : IDL.Func([], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllFaceDescriptors' : IDL.Func(
      [],
      [IDL.Vec(FaceDescriptorRecord)],
      ['query'],
    ),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceStats' : IDL.Func([IDL.Text], [AttendanceStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
  'getFaceDescriptor' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Float64)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveFaceDescriptor' : IDL.Func([IDL.Text, IDL.Vec(IDL.Float64)], [], []),
  'updateEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'timeIn' : IDL.Text,
    'employeeName' : IDL.Text,
    'date' : IDL.Text,
    'employeeId' : IDL.Text,
    'timestamp' : IDL.Int,
    'department' : IDL.Text,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'employeeIdCode' : IDL.Text,
    'department' : IDL.Text,
  });
  const FaceDescriptorRecord = IDL.Record({
    'descriptor' : IDL.Vec(IDL.Float64),
    'employeeId' : IDL.Text,
  });
  const AttendanceStats = IDL.Record({
    'total' : IDL.Nat,
    'present' : IDL.Nat,
    'absent' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAttendanceLogs' : IDL.Func([], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllFaceDescriptors' : IDL.Func(
        [],
        [IDL.Vec(FaceDescriptorRecord)],
        ['query'],
      ),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceStats' : IDL.Func([IDL.Text], [AttendanceStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
    'getFaceDescriptor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Float64)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveFaceDescriptor' : IDL.Func([IDL.Text, IDL.Vec(IDL.Float64)], [], []),
    'updateEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };